<?php


namespace App\DateTime;


class MyDateTime extends \DateTimeImmutable
{
    public function format($format)
    {
        return date($format, $this->time);
//        parent::format($format); // TODO: Change the autogenerated stub
    }

    public function returnString($time)
    {
        $this->time = $time;
        return $this->format('Y-m-d H:i:s');
    }
}